In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
!ls "/content/drive/My Drive/tur_paper_6_feb/maliciou.csv"

'/content/drive/My Drive/tur_paper_6_feb/maliciou.csv'

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:




dataset = pd.read_csv('/content/drive/My Drive/tur_paper_6_feb/maliciou.csv')

In [ ]:
np.random.seed(2)
tf.random.set_seed(2)

In [ ]:
dataset.head(5)

              domain_name    asn             ip  ... n_hypans n_dots   entropy
0             netflix.com  16509    52.49.120.6  ...        0      1  3.459432
1   push.prod.netflix.com  16509  35.167.71.134  ...        0      3  3.975418
2  api-global.netflix.com  16509  52.42.194.172  ...        1      2  3.879664
3              google.com  15169  74.125.68.138  ...        0      1  2.646439
4         ftl.netflix.com  40027     45.57.40.1  ...        0      2  3.373557

[5 rows x 12 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   domain_name     10000 non-null  object
 1   asn             10000 non-null  int64
 2   ip              10000 non-null  object
 3   owner           10000 non-null  object
 4   country_code    10000 non-null  object
 5   malware         10000 non-null  int64
 6   domain _length  10000 non-null  int64
 7   n_letters       10000 non-null  int64
 8   n_number        10000 non-null  int64
 9   n_hypans        10000 non-null  int64
 10  n_dots          10000 non-null  int64
 11  entropy         10000 non-null  float64
dtypes: float64(1), int64(7), object(4)
memory usage: 937.6+ KB

In [ ]:
dataset['asn'].isnull().sum()

0

In [ ]:
dataset['ip'].isnull().sum()

0

In [ ]:
dataset['owner'].isnull().sum()

0

In [ ]:

dataset['country_code'].isnull().sum()

0

In [ ]:

dataset['malware'].isnull().sum()

0

In [ ]:





dataset['domain _length'].isnull().sum()

0

In [ ]:
dataset['n_letters'].isnull().sum()

0

In [ ]:
dataset['n_number'].isnull().sum()

0

In [ ]:
dataset['n_hypans'].isnull().sum()

0

In [ ]:



dataset['n_dots'].isnull().sum()

0

# Text Process

In [ ]:

dataset['entropy'].isnull().sum()

0

In [ ]:
pip install tldextract

Collecting tldextract
  Downloading https://files.pythonhosted.org/packages/7e/62/b6acd3129c5615b9860e670df07fd55b76175b63e6b7f68282c7cad38e9e/tldextract-3.1.0-py2.py3-none-any.whl (87kB)
     |████████████████████████████████| 92kB 4.1MB/s
Collecting requests-file>=1.4
  Downloading https://files.pythonhosted.org/packages/77/86/cdb5e8eaed90796aa83a6d9f75cfbd37af553c47a291cd47bc410ef9bdb2/requests_file-1.5.1-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from tldextract) (2.23.0)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.6/dist-packages (from tldextract) (3.0.12)
Requirement already satisfied: idna in /usr/local/lib/python3.6/dist-packages (from tldextract) (2.10)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from requests-file>=1.4->tldextract) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.1.0->tldextract) (2020.12.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.1.0->tldextract) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.1.0->tldextract) (1.24.3)
Installing collected packages: requests-file, tldextract
Successfully installed requests-file-1.5.1 tldextract-3.1.0

In [ ]:
import tldextract

In [ ]:
extraction_obj = []

In [ ]:
for column in dataset:
  cso = dataset['domain_name']
  extraction_obj.append(cso.values)

In [ ]:
extraction_obj_final = extraction_obj[0]

In [ ]:
len(extraction_obj_final)

10000

In [ ]:
names = [] # store extraction object

In [ ]:
for i in range(0, len(extraction_obj_final)):
  extracted = tldextract.extract(extraction_obj_final[i])
  names.append(extracted)

In [ ]:
names[0:10]

[ExtractResult(subdomain='', domain='netflix', suffix='com'),
 ExtractResult(subdomain='push.prod', domain='netflix', suffix='com'),
 ExtractResult(subdomain='api-global', domain='netflix', suffix='com'),
 ExtractResult(subdomain='', domain='google', suffix='com'),
 ExtractResult(subdomain='ftl', domain='netflix', suffix='com'),
 ExtractResult(subdomain='nrdp.prod.ftl', domain='netflix', suffix='com'),
 ExtractResult(subdomain='ichnaea', domain='netflix', suffix='com'),
 ExtractResult(subdomain='www', domain='google', suffix='com'),
 ExtractResult(subdomain='', domain='microsoft', suffix='com'),
 ExtractResult(subdomain='secure', domain='netflix', suffix='com')]

In [ ]:
#now we will seperate domain name and top level domain, which are stored in domain and suffix respectively

In [ ]:
tld = [] #array to only store top level domain
domain = [] # array to only store domain

In [ ]:
for i in range(0,len(names)):
  tld.append(names[i].suffix)

In [ ]:

tld[0:10] #voila !! now just need to add these to dataset

['com', 'com', 'com', 'com', 'com', 'com', 'com', 'com', 'com', 'com']

In [ ]:
#now in similar fashion doing it for the domain
for i in range(0,len(names)):
  domain.append(names[i].domain)

In [ ]:
domain[0:10] # verify this from the dataset below the first three rows are netflix and then google and all of them have .com in the end

['netflix',
 'netflix',
 'netflix',
 'google',
 'netflix',
 'netflix',
 'netflix',
 'google',
 'microsoft',
 'netflix']

In [ ]:
dataset.head(4)

              domain_name    asn             ip  ... n_hypans n_dots   entropy
0             netflix.com  16509    52.49.120.6  ...        0      1  3.459432
1   push.prod.netflix.com  16509  35.167.71.134  ...        0      3  3.975418
2  api-global.netflix.com  16509  52.42.194.172  ...        1      2  3.879664
3              google.com  15169  74.125.68.138  ...        0      1  2.646439

[4 rows x 12 columns]

In [ ]:
#now add these as seperate features in the dataset

In [ ]:
dataset['tld'] = tld

In [ ]:
dataset['Domain'] = domain

In [ ]:
#drop the domain name column 
dataset.drop(['domain_name'], axis = 1, inplace = True)

# #stepps done until now:
# extracted features from domain name
# removed dots from ip
# kept only company name in the owner column

In [ ]:
#PLEASE COUNT UNIQUE VALUES IN TLD COLUMN AND IN DOMAIN COLUMN IN YOUR OWN NOTEBOOK, AND DONT FORGET TO ADD COMMENTS

In [ ]:
dataset['owner']=dataset['owner'].str.split('-').str[0]

In [ ]:
dataset

         asn               ip  ...     tld               Domain
0      16509      52.49.120.6  ...     com              netflix
1      16509    35.167.71.134  ...     com              netflix
2      16509    52.42.194.172  ...     com              netflix
3      15169    74.125.68.138  ...     com               google
4      40027       45.57.40.1  ...     com              netflix
...      ...              ...  ...     ...                  ...
9995   46606      69.89.31.98  ...     com  californiaroaddream
9996   53831  198.185.159.144  ...     com         callahanward
9997  394695     199.79.62.87  ...   co.in             callisto
9998   26496  184.168.131.241  ...     com            caloaksgc
9999   47583     213.190.6.19  ...  com.co               calpra

[10000 rows x 13 columns]

In [ ]:
dataset['ip'] = dataset['ip'].str.replace('.','') #removes dots from ip column

In [ ]:
dataset.head()

     asn          ip    owner country_code  ...  n_dots   entropy  tld   Domain
0  16509    52491206   AMAZON           US  ...       1  3.459432  com  netflix
1  16509  3516771134   AMAZON           US  ...       3  3.975418  com  netflix
2  16509  5242194172   AMAZON           US  ...       2  3.879664  com  netflix
3  15169  7412568138  GOOGLE            US  ...       1  2.646439  com   google
4  40027     4557401  NETFLIX           US  ...       2  3.373557  com  netflix

[5 rows x 13 columns]

# **from here**

In [ ]:

top_20 = [x for x in dataset.tld.value_counts().sort_values(ascending = False).head(30).index]

In [ ]:
top_20

['com',
 'net',
 'org',
 'ru',
 'com.au',
 'com.br',
 'ml',
 'co.uk',
 'tk',
 'io',
 'de',
 'info',
 'ga',
 'tech',
 'pl',
 'in',
 'ro',
 'cc',
 'nl',
 'tv',
 'fr',
 'biz',
 'us',
 'it',
 'cf',
 'com.ua',
 'co',
 'cn',
 'ca',
 'es']

In [ ]:
for label in top_20:
  dataset[label] = np.where(dataset['tld'] == label , 1,0)

dataset[['tld'] + top_20].head(20)

    tld  com  net  org  ru  com.au  com.br  ...  it  cf  com.ua  co  cn  ca  es
0   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
1   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
2   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
3   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
4   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
5   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
6   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
7   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
8   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
9   com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
10  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
11  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
12  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
13  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
14  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
15  net    0    1    0   0       0       0  ...   0   0       0   0   0   0   0
16  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
17  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0
18  net    0    1    0   0       0       0  ...   0   0       0   0   0   0   0
19  com    1    0    0   0       0       0  ...   0   0       0   0   0   0   0

[20 rows x 31 columns]

In [ ]:
top_20 = [x for x in dataset.Domain.value_counts().sort_values(ascending = False).head(30).index]

In [ ]:
top_20

['apple',
 'doubleverify',
 '000webhostapp',
 'microsoft',
 'google',
 'akadns',
 'yahoo',
 'amazonaws',
 'beget',
 'akamaiedge',
 'amazon',
 'googleapis',
 'facebook',
 'office',
 'altervista',
 'live',
 'fastly',
 'criteo',
 'netflix',
 'adobe',
 'nut',
 'littlematchagirl',
 'mozilla',
 'dotomi',
 'fbcdn',
 'skype',
 'yandex',
 'taboola',
 'windows',
 'rubiconproject']

In [ ]:
 for label in top_20:
  dataset[label] = np.where(dataset['Domain'] == label , 1,0)

 dataset[['Domain'] + top_20].head(30)

              Domain  apple  doubleverify  ...  taboola  windows  rubiconproject
0            netflix      0             0  ...        0        0               0
1            netflix      0             0  ...        0        0               0
2            netflix      0             0  ...        0        0               0
3             google      0             0  ...        0        0               0
4            netflix      0             0  ...        0        0               0
5            netflix      0             0  ...        0        0               0
6            netflix      0             0  ...        0        0               0
7             google      0             0  ...        0        0               0
8          microsoft      0             0  ...        0        0               0
9            netflix      0             0  ...        0        0               0
10           netflix      0             0  ...        0        0               0
11         microsoft      0             0  ...        0        0               0
12          facebook      0             0  ...        0        0               0
13              live      0             0  ...        0        0               0
14        googleapis      0             0  ...        0        0               0
15       doubleclick      0             0  ...        0        0               0
16         microsoft      0             0  ...        0        0               0
17            google      0             0  ...        0        0               0
18       doubleclick      0             0  ...        0        0               0
19           netflix      0             0  ...        0        0               0
20           netflix      0             0  ...        0        0               0
21              live      0             0  ...        0        0               0
22        googleapis      0             0  ...        0        0               0
23  google-analytics      0             0  ...        0        0               0
24             apple      1             0  ...        0        0               0
25           netflix      0             0  ...        0        0               0
26           nflximg      0             0  ...        0        0               0
27           nflximg      0             0  ...        0        0               0
28             skype      0             0  ...        0        0               0
29         microsoft      0             0  ...        0        0               0

[30 rows x 31 columns]

In [ ]:
top_20 = [x for x in dataset.country_code.value_counts().sort_values(ascending = False).head(30).index]

In [ ]:
for label in top_20:
  dataset[label] = np.where(dataset['country_code'] == label , 1,0)

dataset[['country_code'] + top_20].head(30)

   country_code  US  TH  NL  DE  RU  VG  FR  ...  IN  UA  CZ  ES  MY  IT  ZA  KR
0            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
1            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
4            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
5            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
6            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
7            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
8            US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
9            TH   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
10           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
11           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
12           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
13           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
14           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
15           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
16           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
17           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
18           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
19           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
20           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
21           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
22           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
23           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
24           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
25           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
26           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
27           TH   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
28           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
29           US   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0

[30 rows x 31 columns]

In [ ]:
top_20 = [x for x in dataset.owner.value_counts().sort_values(ascending = False).head(30).index]

In [ ]:
for label in top_20:
  dataset[label] = np.where(dataset['owner'] == label , 1,0)

dataset[['owner'] + top_20].head(5)

     owner  AMAZON  GOOGLE   THAI  ...  LI0DE  SINGLEHOP  HIGHWINDS3   SOFTLAYER
0   AMAZON       1        0     0  ...      0          0            0           0
1   AMAZON       1        0     0  ...      0          0            0           0
2   AMAZON       1        0     0  ...      0          0            0           0
3  GOOGLE        0        1     0  ...      0          0            0           0
4  NETFLIX       0        0     0  ...      0          0            0           0

[5 rows x 31 columns]

In [ ]:
dataset

         asn            ip         owner  ... SINGLEHOP  HIGHWINDS3   SOFTLAYER
0      16509      52491206        AMAZON  ...         0            0           0
1      16509    3516771134        AMAZON  ...         0            0           0
2      16509    5242194172        AMAZON  ...         0            0           0
3      15169    7412568138       GOOGLE   ...         0            0           0
4      40027       4557401       NETFLIX  ...         0            0           0
...      ...           ...           ...  ...       ...          ...         ...
9995   46606      69893198  UNIFIEDLAYER  ...         0            0           0
9996   53831  198185159144  SQUARESPACE   ...         0            0           0
9997  394695     199796287        PUBLIC  ...         0            0           0
9998   26496  184168131241            AS  ...         0            0           0
9999   47583     213190619            AS  ...         0            0           0

[10000 rows x 133 columns]

In [ ]:
dataset.drop(['owner', 'country_code','tld','Domain'], axis = 1,inplace=True)

In [ ]:


dataset.head(5)

     asn          ip  malware  ...  SINGLEHOP  HIGHWINDS3   SOFTLAYER
0  16509    52491206        0  ...          0            0           0
1  16509  3516771134        0  ...          0            0           0
2  16509  5242194172        0  ...          0            0           0
3  15169  7412568138        0  ...          0            0           0
4  40027     4557401        0  ...          0            0           0

[5 rows x 129 columns]

In [ ]:
rows = len(dataset.axes[0]) 
cols = len(dataset.axes[1])
print("Number of Rows: " + str(rows)) 
print("Number of Columns: " + str(cols))

Number of Rows: 10000
Number of Columns: 129

# ***TILL HERE***

In [ ]:
x_data = dataset.drop(['malware'],axis = 1)

In [ ]:
y_data = dataset['malware']

In [ ]:
# cat_f = ['com', 'net', 'org', 'ru', 'com.au', 'com.br',
#        'ml', 'co.uk', 'tk', 'io', 'de', 'info', 'ga', 'tech', 'pl', 'in', 'ro',
#        'cc', 'nl', 'tv', 'apple', 'doubleverify', '000webhostapp', 'microsoft',
#        'google', 'akadns', 'yahoo', 'amazonaws', 'beget', 'akamaiedge',
#        'amazon', 'googleapis', 'facebook', 'altervista', 'office', 'live',
#        'fastly', 'criteo', 'netflix', 'adobe', 'US', 'TH', 'NL', 'DE', 'RU',
#        'VG', 'FR', 'CN', 'GB', 'HK', 'AU', 'TR', 'SG', 'CA', 'PL', 'BR', 'LT',
#        'VN', 'JP', 'BG', 'AMAZON', 'GOOGLE ', 'THAI', 'MICROSOFT', 'AS',
#        'AWEX', 'CLOUDFLARENET ', 'VFMNL', 'CONFLUENCE', 'UNIFIEDLAYER',
#        'FASTLY ', 'APPLE', 'HETZNER', 'DOUBLE', 'OVH', 'RMH', 'YAHOO',
#        'FACEBOOK ', 'EDGECAST ', 'NAMECHEAP']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data, test_size = 0.2 , random_state = 2)

In [ ]:
x_train

        asn            ip  domain _length  ...  SINGLEHOP  HIGHWINDS3   SOFTLAYER
8856  18779     232305579              10  ...          0            0           0
1545  45102     478913663              10  ...          0            0           0
8136  45544    1122138925              24  ...          0            0           0
7768  19437    1541612518              22  ...          0            0           0
7782  37963    4710472117              15  ...          0            0           0
...     ...           ...             ...  ...        ...          ...         ...
1099  13335    1041827239              16  ...          0            0           0
2514  15169    3523141163              14  ...          0            0           0
6637  29550     213229682              10  ...          0            0           0
2575   8068     131074214              23  ...          0            0           0
7336  26496  184168131241              17  ...          0            0           0

[8000 rows x 128 columns]

In [ ]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8000 entries, 8856 to 7336
Columns: 128 entries, asn to SOFTLAYER
dtypes: float64(1), int64(126), object(1)
memory usage: 7.9+ MB

#FINDING CHI square  IN TRAIN DATA, chi square returns f score and p value

In [ ]:
from sklearn.feature_selection import chi2, SelectKBest

In [ ]:
select_feature = SelectKBest(chi2, k =48).fit(x_train,y_train)

#features with high f score an lower p values will be selected

In [ ]:
selected_features = pd.DataFrame({'Feature':list(x_train.columns), 'Scores' :select_feature.scores_})

In [ ]:
selected_features.sort_values(by='Scores',ascending =False).head(12)

            Feature        Scores
1                ip  8.342845e+09
0               asn  6.798845e+07
98           AMAZON  5.342678e+02
100            THAI  4.670000e+02
69               TH  4.102854e+02
6            n_dots  4.003766e+02
2    domain _length  3.731030e+02
99          GOOGLE   3.401417e+02
5          n_hypans  3.290963e+02
68               US  3.202597e+02
103            AWEX  2.970000e+02
101       MICROSOFT  2.942201e+02

#3 numerical and 9 categorical features selected

In [ ]:
x_train_chi_12 = select_feature.transform(x_train)
x_test_chi_12 = select_feature.transform(x_test)

In [ ]:
x_train_chi_12[1]

array([45102, '478913663', 10, 9, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [ ]:
 from sklearn.preprocessing import MinMaxScaler
 rs = MinMaxScaler()

 x_train_scaled = rs.fit_transform(x_train_chi_12)

In [ ]:
x_test_scaled = rs.transform(x_test_chi_12)

In [ ]:
from sklearn import svm

In [ ]:
svc = svm.SVC()

In [ ]:
svc.fit(x_train_scaled,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
prediction_svc = svc.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix
matrix_svc = confusion_matrix(y_test, prediction_svc,)
matrix_svc = confusion_matrix(y_test,prediction_svc,)
matrix_svc

array([[891, 109],
       [130, 870]])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
cr_svc = classification_report(y_test,prediction_svc,digits =5)

In [ ]:
print(cr_svc)

              precision    recall  f1-score   support

           0    0.87267   0.89100   0.88174      1000
           1    0.88866   0.87000   0.87923      1000

    accuracy                        0.88050      2000
   macro avg    0.88067   0.88050   0.88049      2000
weighted avg    0.88067   0.88050   0.88049      2000

#RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(random_state = 2)

In [ ]:
rf.fit(x_train_scaled,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=2, verbose=0,
                       warm_start=False)

In [ ]:
prediction_rf = rf.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix
matrix_rf = confusion_matrix(y_test, prediction_rf,)
matrix_rf = confusion_matrix(y_test,prediction_rf,)
matrix_rf

array([[894, 106],
       [ 68, 932]])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
cr_rf = classification_report(y_test,prediction_rf,digits =5)

In [ ]:
print(cr_rf)

              precision    recall  f1-score   support

           0    0.92931   0.89400   0.91131      1000
           1    0.89788   0.93200   0.91462      1000

    accuracy                        0.91300      2000
   macro avg    0.91360   0.91300   0.91297      2000
weighted avg    0.91360   0.91300   0.91297      2000

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

In [ ]:
gb = GradientBoostingClassifier( random_state = 2)

In [ ]:
gb.fit(x_train_scaled,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=2, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [ ]:
prediction_gb = gb.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix
matrix_gb = confusion_matrix(y_test, prediction_gb,)
matrix_gb = confusion_matrix(y_test,prediction_gb,)
matrix_gb

array([[888, 112],
       [ 85, 915]])

In [ ]:
cr_gb = classification_report(y_test,prediction_gb,digits =5)

In [ ]:
print(cr_gb)

              precision    recall  f1-score   support

           0    0.91675   0.89200   0.90421      1000
           1    0.89484   0.91900   0.90676      1000

    accuracy                        0.90550      2000
   macro avg    0.90580   0.90550   0.90548      2000
weighted avg    0.90580   0.90550   0.90548      2000